name: todo_app
description: A simple to-do application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.1.0"

dependencies:
  flutter:
    sdk: flutter
  anxeb_flutter:
    path: ../anxeb-flutter
  cupertino_icons: 1.0.5
  device_info_plus: 8.1.0
  package_info_plus: 3.0.3
  sentry_flutter: 6.20.1
  flutter_html: 2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.11.0
  flutter_lints: 2.0.1
  flutter_native_splash: 2.2.16
  integration_test:
    sdk: flutter
  mockito: 5.3.2
  test: 1.22.0

dependency_overrides:
  xml: ^6.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_ios: "assets/icons/ios.png"
  image_path_android: "assets/icons/android.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/landing/splash.png
  color_dark: "#000000"
  image_dark: assets/images/landing/splash.png

  android_12:
    color: "#ffffff"
    image: assets/images/landing/splash.png
    color_dark: "#000000"
    image_dark: assets/images/landing/splash.png

  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/icons/
    - assets/images/brand/
    - assets/images/social/
    - assets/images/landing/
    - assets/images/common/
